const experience = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2007 - 2011",
    title: "Bachelor - Public Affairs Administration",
    description: "Shanghai University of Electric Power",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2016 - 2018",
    title: "Post-Degree Diploma - Marketing Management",
    description: "Langara College",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2022 - 2022",
    title: "Diploma - Full Stack Web Development",
    description: "Lighthouse Labs",
  },
  {
    id: 4,
    category: "work",
    icon: "icon-briefcase",
    year: "2009 - 2015",
    title: "Wedding Planner",
    description: "Shanghai Bao Hui Wedding Planning Ltd.",
  },
  {
    id: 5,
    category: "work",
    icon: "icon-briefcase",
    year: "2012 - 2015",
    title: "Sales Manager",
    description: "Shanghai Bao Hui Wedding Planning Ltd.",
  },
  {
    id: 6,
    category: "work",
    icon: "icon-briefcase",
    year: "2017 - 2020",
    title: "Sales Associate",
    description: "Canuck Volleyball Vancouver",
  },
  {
    id: 7,
    category: "work",
    icon: "icon-briefcase",
    year: "2020 - 2022",
    title: "Digital Printing Machine Operator",
    description: "Oddball Workshop Inc.",
  },
  {
    id: 8,
    category: "work",
    icon: "icon-briefcase",
    year: "2022 - Present",
    title: "Freelance Full-Stack Developer",
    description: "",
  },
];

export default experience;
